/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "inverse-primary": "#005ac2",
                "tertiary-container": "#00a572",
                "background": "#0b1326",
                "primary-fixed-dim": "#adc6ff",
                "on-secondary-fixed-variant": "#2f2ebe",
                "inverse-surface": "#dae2fd",
                "tertiary": "#4edea3",
                "on-primary-fixed": "#001a42",
                "surface-container-low": "#131b2e",
                "surface-container-highest": "#2d3449",
                "tertiary-fixed": "#6ffbbe",
                "on-tertiary-fixed": "#002113",
                "on-primary-fixed-variant": "#004395",
                "surface-container": "#171f33",
                "primary-container": "#4d8eff",
                "on-secondary-container": "#b0b2ff",
                "on-primary": "#002e6a",
                "on-tertiary": "#003824",
                "on-secondary": "#1000a9",
                "error-container": "#93000a",
                "surface-container-high": "#222a3d",
                "secondary-container": "#3131c0",
                "error": "#ffb4ab",
                "outline": "#8c909f",
                "tertiary-fixed-dim": "#4edea3",
                "on-tertiary-container": "#00311f",
                "outline-variant": "#424754",
                "secondary": "#c0c1ff",
                "primary": "#adc6ff",
                "on-secondary-fixed": "#07006c",
                "on-tertiary-fixed-variant": "#005236",
                "surface": "#0b1326",
                "on-surface-variant": "#c2c6d6",
                "secondary-fixed-dim": "#c0c1ff",
                "surface-bright": "#31394d",
                "on-primary-container": "#00285d",
                "surface-dim": "#0b1326",
                "surface-variant": "#2d3449",
                "on-surface": "#dae2fd",
                "on-error": "#690005",
                "inverse-on-surface": "#283044",
                "primary-fixed": "#d8e2ff",
                "surface-tint": "#adc6ff",
                "surface-container-lowest": "#060e20",
                "on-error-container": "#ffdad6",
                "on-background": "#dae2fd",
                "secondary-fixed": "#e1e0ff"
            },
            fontFamily: {
                "headline": ["Inter"],
                "body": ["Inter"],
                "label": ["Space Grotesk"],
                "mono": ["Fira Code"]
            },
            borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
        },
    },
    plugins: [],
}
